# Publish the state of each joint in /joint_states topic-----------------------------------
ur10e_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Specifies how to control each individual joint -----------------------------------
arm_controller:
   type: "position_controllers/JointGroupPositionController"
   joints:
     - joint_1
     - joint_2
     - joint_3
     - joint_4
     - joint_5
     - joint_6



hand_controller:
   type: "position_controllers/JointGroupPositionController"
   joints:
     - joint_8_grasping_1
     - joint_9_grasping_2
